<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit211d5fff23ca206c4c4c94d48c82d9d1
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Bluehost\Plugin\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Bluehost\Plugin\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit211d5fff23ca206c4c4c94d48c82d9d1', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Bluehost\Plugin\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit211d5fff23ca206c4c4c94d48c82d9d1', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Bluehost\Plugin\Composer\Autoload\ComposerStaticInit211d5fff23ca206c4c4c94d48c82d9d1::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
