<?php
acf_add_local_field_group(array(
    'key'                           => 'group_page_5G9hFG9cgxnmHEHT',
    'title'                         => esc_attr__('Blog Post Options','autlines'),
    'fields' => array(
        /*-------------------------------------------------------------------
        ==  Blog Setting
        -------------------------------------------------------------------*/
        array(
            'key'                   => 'field_XS5vnP8HHQGBF',
            'label'                 => '<span class="dashicons dashicons-grid-view"></span>'.esc_attr__('Blog Setting','autlines'),
            'name'                  => '',
            'type'                  => 'tab',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'placement'             => 'left',
            'endpoint'              => 0,
        ),
        array(
            'key'                   => 'field_RSzSD1O0niiyA',
            'label'                 => esc_attr__('Post Style','autlines'),
            'name'                  => 'blog_archive_style',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'default'                       => esc_attr__('Default','autlines'),
                'default-two'                   => esc_attr__('Default Two','autlines'),
                'grid'                          => esc_attr__('Grid','autlines'),
            ),
            'default_value' => array(
                0                                   => 'default',
            ),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),

        array(
            'key'                   => 'field_fUdpQeSH3x3WCym5',
            'label'                 => esc_attr__('Post per page','autlines'),
            'name'                  => 'post_per_page',
            'type'                  => 'text',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                                 => '',
                'class'                                 => '',
                'id'                                    => '',
            ),
            'choices'               => array(),
            'default_value'         => '9',
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),

        array(
            'key'                   => 'field_6CjgumMvyzb23cpage',
            'label'                 => esc_attr__('Blog Animation','autlines'),
            'name'                  => 'blog_animation',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'disable'                =>         esc_attr__('Disable','autlines'),
                'fadeIn'                 =>         esc_attr__('fadeIn','autlines'),
                'flipXIn'                =>         esc_attr__('flipXIn','autlines'),
                'flipYIn'                =>         esc_attr__('flipYIn','autlines'),
                'flipBounceXIn'          =>         esc_attr__('flipBounceXIn','autlines'),
                'flipBounceYIn'          =>         esc_attr__('flipBounceYIn','autlines'),
                'swoopIn'                =>         esc_attr__('swoopIn','autlines'),
                'raise'                  =>         esc_attr__('raise','autlines'),
                'whirlIn'                =>         esc_attr__('whirlIn','autlines'),
                'shrinkIn'               =>         esc_attr__('shrinkIn','autlines'),
                'expandIn'               =>         esc_attr__('expandIn','autlines'),
                'bounceIn'               =>         esc_attr__('bounceIn','autlines'),
                'bounceUpIn'             =>         esc_attr__('bounceUpIn','autlines'),
                'bounceDownIn'           =>         esc_attr__('bounceDownIn','autlines'),
                'bounceLeftIn'           =>         esc_attr__('bounceLeftIn','autlines'),
                'bounceRightIn'          =>         esc_attr__('bounceRightIn','autlines'),
                'slideUpIn'              =>         esc_attr__('slideUpIn','autlines'),
                'slideDownIn'            =>         esc_attr__('slideDownIn','autlines'),
                'slideLeftIn'            =>         esc_attr__('slideLeftIn','autlines'),
                'slideRightIn'           =>         esc_attr__('slideRightIn','autlines'),
                'slideUpBigIn'           =>         esc_attr__('slideUpBigIn','autlines'),
                'slideDownBigIn'         =>         esc_attr__('slideDownBigIn','autlines'),
                'slideLeftBigIn'         =>         esc_attr__('slideLeftBigIn','autlines'),
                'slideRightBigIn'        =>         esc_attr__('slideRightBigIn','autlines'),
                'perspectiveUpIn'        =>         esc_attr__('perspectiveUpIn','autlines'),
                'perspectiveDownIn'      =>         esc_attr__('perspectiveDownIn','autlines'),
                'perspectiveLeftIn'      =>         esc_attr__('perspectiveLeftIn','autlines'),
                'perspectiveRightIn'     =>         esc_attr__('perspectiveRightIn','autlines'),
                'zoomIn'                 =>         esc_attr__('zoomIn','autlines'),
                'slideInRightVeryBig'    =>         esc_attr__('slideInRightVeryBig','autlines'),
                'slideInLeftVeryBig'     =>         esc_attr__('slideInLeftVeryBig','autlines'),
            ),
            'default_value'         => array(),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),

        array(
            'key'                   => 'field_H3fjCCwsxjwJpcpage',
            'label'                 => esc_attr__('Blog Pagination','autlines'),
            'name'                  => 'blog_pagination',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'standard'                   => esc_attr__('Default','autlines'),
                'load_more'                  => esc_attr__('Load More','autlines'),
            ),
            'default_value' => array(
                0                                   => 'standard',
            ),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),
/*-------------------------------------------------------------------
  ==  Sidebar Setting
  -------------------------------------------------------------------*/
        array(
            'key'                   => 'field_ghYeEwwoh6Qeu',
            'label'                 => '<span class="dashicons dashicons-align-right"></span>'.esc_attr__('Sidebar Setting','autlines'),
            'name'                  => '',
            'type'                  => 'tab',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'placement'             => 'left',
            'endpoint'              => 0,
        ),
        array(
            'key'                   => 'field_adF1VkIkBqala',
            'label'                 => esc_attr__('Sidebar','autlines'),
            'name'                  => 'blog_template_sidebar',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'disable'                   => esc_attr__('Disable','autlines'),
                'left'                      => esc_attr__('Left','autlines'),
                'right'                     => esc_attr__('Right','autlines'),
            ),
            'default_value' => array(
                0                                   => 'disable',
            ),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),
    ),
    'location' => array(
        array(
            array(
                'param'                                 => 'page_template',
                'operator'                              => '==',
                'value'                                 => 'template-blog.php',
            ),
        ),
    ),
    'menu_order'                    => 0,
    'position'                      => 'normal',
    'style'                         => 'default',
    'label_placement'               => 'top',
    'instruction_placement'         => 'label',
    'hide_on_screen'                => '',
    'active'                        => 1,
    'description'                   => '',
));